name: Build and Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get version from tag
      run: |
        export PACKAGE_VERSION=$(echo $GITHUB_REF | cut -d '/' -f 3)
        sed -i "s/version =.*/version = $PACKAGE_VERSION/" setup.cfg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install twine

    - name: Build and Publish Package
      run: |
        python -m build
        twine upload dist/* -u __token__ -p ${{ secrets.PYPI_PWD }}
